[2024-10-09T09:27:16.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-09T09:27:16.506+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-09T09:27:11.965134+00:00 [queued]>
[2024-10-09T09:27:16.528+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-09T09:27:11.965134+00:00 [queued]>
[2024-10-09T09:27:16.530+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-09T09:27:16.569+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract> on 2024-10-09 09:27:11.965134+00:00
[2024-10-09T09:27:16.579+0000] {standard_task_runner.py:72} INFO - Started process 50 to run task
[2024-10-09T09:27:16.586+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'manual__2024-10-09T09:27:11.965134+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmp1i21knxo']
[2024-10-09T09:27:16.594+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask extract
[2024-10-09T09:27:16.627+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:209: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-09T09:27:16.712+0000] {task_command.py:467} INFO - Running <TaskInstance: EL.extract manual__2024-10-09T09:27:11.965134+00:00 [running]> on host 6da5f868324e
[2024-10-09T09:27:16.854+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T09:27:11.965134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-09T09:27:11.965134+00:00'
[2024-10-09T09:27:16.858+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-09T09:27:16.904+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-09T09:27:16.907+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'xvfb-run --server-args="-screen 0 1920x1080x24" python3 /opt/airflow/scripts/scrape.py']
[2024-10-09T09:27:16.921+0000] {subprocess.py:86} INFO - Output:
[2024-10-09T09:27:19.662+0000] {subprocess.py:93} INFO - INFO:root:Opening IMDb page...
[2024-10-09T09:27:25.195+0000] {subprocess.py:93} INFO - INFO:root:Page loaded, waiting for elements...
[2024-10-09T09:27:25.261+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-09T09:27:25.262+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/scrape.py", line 198, in <module>
[2024-10-09T09:27:25.265+0000] {subprocess.py:93} INFO -     EC.presence_of_element_located(By.XPATH, "//ul[contains(@class, 'ipc-metadata-list')]//li[contains(@class, 'ipc-metadata-list-summary-item')]")
[2024-10-09T09:27:25.267+0000] {subprocess.py:93} INFO - TypeError: presence_of_element_located() takes 1 positional argument but 2 were given
[2024-10-09T09:27:25.367+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-09T09:27:25.381+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-09T09:27:25.388+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, run_id=manual__2024-10-09T09:27:11.965134+00:00, execution_date=20241009T092711, start_date=20241009T092716, end_date=20241009T092725
[2024-10-09T09:27:25.413+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-09T09:27:25.415+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 50)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-09T09:27:25.462+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-09T09:27:25.512+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-09T09:27:25.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
