[2024-10-05T10:04:25.981+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T10:04:25.991+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T10:04:25.992+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-05T10:04:26.019+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): extract> on 2024-10-04 00:00:00+00:00
[2024-10-05T10:04:26.025+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2024-10-05T10:04:26.031+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmpp0ioml0r']
[2024-10-05T10:04:26.035+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask extract
[2024-10-05T10:04:26.057+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-05T10:04:26.098+0000] {task_command.py:423} INFO - Running <TaskInstance: EL.extract scheduled__2024-10-04T00:00:00+00:00 [running]> on host 0034d4dc3cc9
[2024-10-05T10:04:26.201+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-10-05T10:04:26.203+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-05T10:04:26.205+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/scrape.py']
[2024-10-05T10:04:26.213+0000] {subprocess.py:86} INFO - Output:
[2024-10-05T10:04:27.384+0000] {subprocess.py:93} INFO - INFO:WDM:====== WebDriver manager ======
[2024-10-05T10:04:27.620+0000] {subprocess.py:93} INFO - INFO:WDM:Get LATEST chromedriver version for google-chrome
[2024-10-05T10:04:27.920+0000] {subprocess.py:93} INFO - INFO:WDM:Get LATEST chromedriver version for google-chrome
[2024-10-05T10:04:28.075+0000] {subprocess.py:93} INFO - INFO:WDM:There is no [linux64] chromedriver "129.0.6668.89" for browser google-chrome "129.0.6668" in cache
[2024-10-05T10:04:28.077+0000] {subprocess.py:93} INFO - INFO:WDM:Get LATEST chromedriver version for google-chrome
[2024-10-05T10:04:28.519+0000] {subprocess.py:93} INFO - INFO:WDM:WebDriver version 129.0.6668.89 selected
[2024-10-05T10:04:28.525+0000] {subprocess.py:93} INFO - INFO:WDM:Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.89/linux64/chromedriver-linux64.zip
[2024-10-05T10:04:28.532+0000] {subprocess.py:93} INFO - INFO:WDM:About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.89/linux64/chromedriver-linux64.zip
[2024-10-05T10:04:28.780+0000] {subprocess.py:93} INFO - INFO:WDM:Driver downloading response is 200
[2024-10-05T10:04:37.146+0000] {subprocess.py:93} INFO - INFO:WDM:Get LATEST chromedriver version for google-chrome
[2024-10-05T10:04:37.474+0000] {subprocess.py:93} INFO - INFO:WDM:Driver has been saved in cache [/home/airflow/.wdm/drivers/chromedriver/linux64/129.0.6668.89]
[2024-10-05T10:04:38.280+0000] {subprocess.py:93} INFO - INFO:root:Opening IMDb page...
[2024-10-05T10:04:43.942+0000] {subprocess.py:93} INFO - INFO:root:Page loaded, waiting for elements...
[2024-10-05T10:05:14.259+0000] {subprocess.py:93} INFO - ERROR:root:Timeout: Element not found within the given time, saving screenshot...
[2024-10-05T10:05:14.509+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-05T10:05:14.511+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/scrape.py", line 42, in <module>
[2024-10-05T10:05:14.516+0000] {subprocess.py:93} INFO -     WebDriverWait(driver, 30).until(
[2024-10-05T10:05:14.517+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 105, in until
[2024-10-05T10:05:14.519+0000] {subprocess.py:93} INFO -     raise TimeoutException(message, screen, stacktrace)
[2024-10-05T10:05:14.521+0000] {subprocess.py:93} INFO - selenium.common.exceptions.TimeoutException: Message:
[2024-10-05T10:05:14.522+0000] {subprocess.py:93} INFO - Stacktrace:
[2024-10-05T10:05:14.523+0000] {subprocess.py:93} INFO - #0 0x555b97daf02a <unknown>
[2024-10-05T10:05:14.524+0000] {subprocess.py:93} INFO - #1 0x555b97a955e0 <unknown>
[2024-10-05T10:05:14.526+0000] {subprocess.py:93} INFO - #2 0x555b97ae4be8 <unknown>
[2024-10-05T10:05:14.527+0000] {subprocess.py:93} INFO - #3 0x555b97ae4e81 <unknown>
[2024-10-05T10:05:14.529+0000] {subprocess.py:93} INFO - #4 0x555b97b2b8c4 <unknown>
[2024-10-05T10:05:14.530+0000] {subprocess.py:93} INFO - #5 0x555b97b09b4d <unknown>
[2024-10-05T10:05:14.531+0000] {subprocess.py:93} INFO - #6 0x555b97b28d7d <unknown>
[2024-10-05T10:05:14.532+0000] {subprocess.py:93} INFO - #7 0x555b97b098c3 <unknown>
[2024-10-05T10:05:14.533+0000] {subprocess.py:93} INFO - #8 0x555b97ad76b3 <unknown>
[2024-10-05T10:05:14.535+0000] {subprocess.py:93} INFO - #9 0x555b97ad868e <unknown>
[2024-10-05T10:05:14.536+0000] {subprocess.py:93} INFO - #10 0x555b97d79a2b <unknown>
[2024-10-05T10:05:14.537+0000] {subprocess.py:93} INFO - #11 0x555b97d7d9b1 <unknown>
[2024-10-05T10:05:14.538+0000] {subprocess.py:93} INFO - #12 0x555b97d66225 <unknown>
[2024-10-05T10:05:14.540+0000] {subprocess.py:93} INFO - #13 0x555b97d7e532 <unknown>
[2024-10-05T10:05:14.540+0000] {subprocess.py:93} INFO - #14 0x555b97d4b38f <unknown>
[2024-10-05T10:05:14.541+0000] {subprocess.py:93} INFO - #15 0x555b97d9df28 <unknown>
[2024-10-05T10:05:14.542+0000] {subprocess.py:93} INFO - #16 0x555b97d9e0f3 <unknown>
[2024-10-05T10:05:14.543+0000] {subprocess.py:93} INFO - #17 0x555b97dade7c <unknown>
[2024-10-05T10:05:14.544+0000] {subprocess.py:93} INFO - #18 0x7fecc5a59144 <unknown>
[2024-10-05T10:05:14.545+0000] {subprocess.py:93} INFO - 
[2024-10-05T10:05:14.637+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-05T10:05:14.651+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-05T10:05:14.659+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, execution_date=20241004T000000, start_date=20241005T100425, end_date=20241005T100514
[2024-10-05T10:05:14.820+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 177)
[2024-10-05T10:05:14.858+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-05T10:05:14.882+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T10:29:10.088+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T10:29:10.112+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T10:29:10.113+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-05T10:29:10.150+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): extract> on 2024-10-04 00:00:00+00:00
[2024-10-05T10:29:10.162+0000] {standard_task_runner.py:60} INFO - Started process 178 to run task
[2024-10-05T10:29:10.170+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmplagptvw8']
[2024-10-05T10:29:10.176+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask extract
[2024-10-05T10:29:10.218+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-05T10:29:10.314+0000] {task_command.py:423} INFO - Running <TaskInstance: EL.extract scheduled__2024-10-04T00:00:00+00:00 [running]> on host 7b14ee7321eb
[2024-10-05T10:29:10.533+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-10-05T10:29:10.538+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-05T10:29:10.540+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'xvfb-run --server-args="-screen 0 1920x1080x24" python3 /opt/airflow/scripts/scrape.py']
[2024-10-05T10:29:10.558+0000] {subprocess.py:86} INFO - Output:
[2024-10-05T10:29:12.424+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-05T10:29:12.425+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/scrape.py", line 32, in <module>
[2024-10-05T10:29:12.428+0000] {subprocess.py:93} INFO -     driver = webdriver.Chrome(service=Service(ChromeDriverManager(version="129.0.6668.89").install()), options=chrome_options)
[2024-10-05T10:29:12.429+0000] {subprocess.py:93} INFO - TypeError: __init__() got an unexpected keyword argument 'version'
[2024-10-05T10:29:12.615+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-05T10:29:12.631+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-05T10:29:12.638+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, execution_date=20241004T000000, start_date=20241005T102910, end_date=20241005T102912
[2024-10-05T10:29:12.664+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 178)
[2024-10-05T10:29:12.685+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-05T10:29:12.745+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
