[2024-10-04T13:51:08.275+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T13:51:04.664939+00:00 [queued]>
[2024-10-04T13:51:08.301+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T13:51:04.664939+00:00 [queued]>
[2024-10-04T13:51:08.302+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-04T13:51:08.347+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): extract> on 2024-10-04 13:51:04.664939+00:00
[2024-10-04T13:51:08.357+0000] {standard_task_runner.py:60} INFO - Started process 189 to run task
[2024-10-04T13:51:08.364+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'manual__2024-10-04T13:51:04.664939+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmp58z0ys2i']
[2024-10-04T13:51:08.369+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2024-10-04T13:51:08.408+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T13:51:08.489+0000] {task_command.py:423} INFO - Running <TaskInstance: EL.extract manual__2024-10-04T13:51:04.664939+00:00 [running]> on host b622cd3c4abe
[2024-10-04T13:51:08.681+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T13:51:04.664939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T13:51:04.664939+00:00'
[2024-10-04T13:51:08.684+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-04T13:51:08.687+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/extract.py']
[2024-10-04T13:51:08.702+0000] {subprocess.py:86} INFO - Output:
[2024-10-04T13:51:08.762+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/scripts/extract.py': [Errno 2] No such file or directory
[2024-10-04T13:51:08.769+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-04T13:51:08.800+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-04T13:51:08.809+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, execution_date=20241004T135104, start_date=20241004T135108, end_date=20241004T135108
[2024-10-04T13:51:08.835+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 189)
[2024-10-04T13:51:08.861+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T13:51:08.907+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
