[2024-10-08T18:45:52.911+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T18:45:52.958+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-08T18:45:44.766868+00:00 [queued]>
[2024-10-08T18:45:52.981+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-08T18:45:44.766868+00:00 [queued]>
[2024-10-08T18:45:52.984+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-08T18:45:53.019+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract> on 2024-10-08 18:45:44.766868+00:00
[2024-10-08T18:45:53.032+0000] {standard_task_runner.py:72} INFO - Started process 51 to run task
[2024-10-08T18:45:53.044+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'manual__2024-10-08T18:45:44.766868+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmpcf1q9q3p']
[2024-10-08T18:45:53.053+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask extract
[2024-10-08T18:45:53.110+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:209: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-08T18:45:53.203+0000] {task_command.py:467} INFO - Running <TaskInstance: EL.extract manual__2024-10-08T18:45:44.766868+00:00 [running]> on host d20753ffd9f2
[2024-10-08T18:45:53.401+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T18:45:44.766868+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T18:45:44.766868+00:00'
[2024-10-08T18:45:53.406+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T18:45:53.476+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-08T18:45:53.479+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'xvfb-run --server-args="-screen 0 1920x1080x24" python3 /opt/airflow/scripts/scrape.py']
[2024-10-08T18:45:53.500+0000] {subprocess.py:86} INFO - Output:
[2024-10-08T18:45:56.767+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-08T18:45:56.770+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/scrape.py", line 32, in <module>
[2024-10-08T18:45:56.773+0000] {subprocess.py:93} INFO -     driver = webdriver.Chrome(ChromeDriverManager(version="129.0.6668.89").install())
[2024-10-08T18:45:56.782+0000] {subprocess.py:93} INFO - TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'version'
[2024-10-08T18:45:57.067+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-08T18:45:57.113+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-08T18:45:57.131+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, run_id=manual__2024-10-08T18:45:44.766868+00:00, execution_date=20241008T184544, start_date=20241008T184552, end_date=20241008T184557
[2024-10-08T18:45:57.206+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T18:45:57.211+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task extract (Bash command failed. The command returned a non-zero exit code 1.; 51)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-08T18:45:57.278+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-08T18:45:57.362+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T18:45:57.376+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
