[2024-10-04T14:00:11.379+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T14:00:07.066803+00:00 [queued]>
[2024-10-04T14:00:11.402+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T14:00:07.066803+00:00 [queued]>
[2024-10-04T14:00:11.404+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-04T14:00:11.452+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): extract> on 2024-10-04 14:00:07.066803+00:00
[2024-10-04T14:00:11.463+0000] {standard_task_runner.py:60} INFO - Started process 202 to run task
[2024-10-04T14:00:11.470+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'manual__2024-10-04T14:00:07.066803+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmptnavya_o']
[2024-10-04T14:00:11.476+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2024-10-04T14:00:11.517+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T14:00:11.610+0000] {task_command.py:423} INFO - Running <TaskInstance: EL.extract manual__2024-10-04T14:00:07.066803+00:00 [running]> on host c4daf3b4a5a2
[2024-10-04T14:00:11.812+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T14:00:07.066803+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T14:00:07.066803+00:00'
[2024-10-04T14:00:11.816+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-04T14:00:11.818+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/extract.py']
[2024-10-04T14:00:11.838+0000] {subprocess.py:86} INFO - Output:
[2024-10-04T14:00:11.924+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/scripts/extract.py': [Errno 2] No such file or directory
[2024-10-04T14:00:11.935+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-04T14:00:11.959+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-04T14:00:11.970+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, execution_date=20241004T140007, start_date=20241004T140011, end_date=20241004T140011
[2024-10-04T14:00:12.016+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 202)
[2024-10-04T14:00:12.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T14:00:12.098+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
