[2024-10-04T13:45:16.855+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T13:45:12.003826+00:00 [queued]>
[2024-10-04T13:45:16.890+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T13:45:12.003826+00:00 [queued]>
[2024-10-04T13:45:16.892+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-04T13:45:16.970+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): extract> on 2024-10-04 13:45:12.003826+00:00
[2024-10-04T13:45:16.984+0000] {standard_task_runner.py:60} INFO - Started process 199 to run task
[2024-10-04T13:45:16.996+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'manual__2024-10-04T13:45:12.003826+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmpqpzk5ari']
[2024-10-04T13:45:17.003+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2024-10-04T13:45:17.071+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T13:45:17.202+0000] {task_command.py:423} INFO - Running <TaskInstance: EL.extract manual__2024-10-04T13:45:12.003826+00:00 [running]> on host d4de17cb2ec2
[2024-10-04T13:45:17.463+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T13:45:12.003826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T13:45:12.003826+00:00'
[2024-10-04T13:45:17.468+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-04T13:45:17.471+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/extract.py']
[2024-10-04T13:45:17.494+0000] {subprocess.py:86} INFO - Output:
[2024-10-04T13:45:17.586+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/scripts/extract.py': [Errno 2] No such file or directory
[2024-10-04T13:45:17.597+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-04T13:45:17.627+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-04T13:45:17.637+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, execution_date=20241004T134512, start_date=20241004T134516, end_date=20241004T134517
[2024-10-04T13:45:17.686+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 199)
[2024-10-04T13:45:17.736+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T13:45:17.810+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
