[2024-10-04T13:27:40.534+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T13:27:36.249296+00:00 [queued]>
[2024-10-04T13:27:40.566+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EL.extract manual__2024-10-04T13:27:36.249296+00:00 [queued]>
[2024-10-04T13:27:40.568+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-04T13:27:40.614+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): extract> on 2024-10-04 13:27:36.249296+00:00
[2024-10-04T13:27:40.628+0000] {standard_task_runner.py:60} INFO - Started process 200 to run task
[2024-10-04T13:27:40.640+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'extract', 'manual__2024-10-04T13:27:36.249296+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scrape_dag.py', '--cfg-path', '/tmp/tmpd11ziabc']
[2024-10-04T13:27:40.648+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract
[2024-10-04T13:27:40.717+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T13:27:40.870+0000] {task_command.py:423} INFO - Running <TaskInstance: EL.extract manual__2024-10-04T13:27:36.249296+00:00 [running]> on host e669e9932592
[2024-10-04T13:27:41.166+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bmw' AIRFLOW_CTX_DAG_ID='EL' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T13:27:36.249296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T13:27:36.249296+00:00'
[2024-10-04T13:27:41.171+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-04T13:27:41.176+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/extract.py']
[2024-10-04T13:27:41.199+0000] {subprocess.py:86} INFO - Output:
[2024-10-04T13:27:41.306+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/scripts/extract.py': [Errno 2] No such file or directory
[2024-10-04T13:27:41.323+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-04T13:27:41.359+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-04T13:27:41.372+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=EL, task_id=extract, execution_date=20241004T132736, start_date=20241004T132740, end_date=20241004T132741
[2024-10-04T13:27:41.426+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 200)
[2024-10-04T13:27:41.458+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-04T13:27:41.540+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
